name: deploy-daily
run-name: Deploy jumple day, daily
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'
jobs:
  deploy-from-assets:
    runs-on: ubuntu-latest
    environment: daily-deploy
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          path: ${{ github.workspace }}/jumple
      - uses: actions/checkout@v4
        with:
          repository: 'spiritov/jumple-assets'
          ref: 'main'
          ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}
          path: ${{ github.workspace }}/jumple-assets
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Copy new day assets to jumple
        run: python jumple/deploy.py
      - name: Commit new day assets to jumple
        run: |
          cd ${{ github.workspace }}/jumple          
          git config --global user.name 'Spiritov'
          git config --global user.email 'spiritov@users.noreply.github.com'
          git add jumple_day_number.txt assets/maps/
          git commit -m "Deploy new day"
          git push
