name: deploy-daily
run-name: Deploy jumple day, daily
on:
  workflow_run:
    workflows: ["Build"]
    types: [requested]
    branches:
      - 'main'
jobs:
  deploy-from-assets:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.repository }}
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: 'spiritov/jumple-assets'
      - run: ls .
