name: deploy-daily
run-name: Deploy jumple day, daily
on: workflow_dispatch
jobs:
  deploy-from-assets:
    runs-on: ubuntu-latest
    environment: daily-deploy
    steps:
      - run: echo ${{ github.repository }}
      - run: ssh-add - <<< ${{ secrets.PRIVATE_SSH_KEY }}
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: 'spiritov/jumple-assets'
          ref: 'main'
      - run: ls .
